### PR TITLE
Add Download as PDF

### PR DESCRIPTION
**Pull request by attah**
Feel free to use this only as inspiration and make something nicer.

### CODE REVIEW

**Comment by Logic-gate** [comment]
I'll merge this, I just need to commit my local version which has a few fixes, especially for file names. It's not the best of solutions, but I have local version which saves files by their id rather than name. Rationale, if you have 2 completely different files with the same name, they will be overwritten by each other. A solution is to checksum, but what if you updated that document?? the only constant is id. 

I'll merge this after optimizing my local version. 

Thanks for the contribution.

**Comment by attah** [comment]
Interesting dilemma. I don't mind getting involved in that discussion, but we should probably move it at least to a new issue. I even think Cargo deserves its own thread on the SFOS forum :)
There are some remedies (calling them solutions is a bit strong) i can think of for that. 
1) Ask the user to replace the file with the same name (even for updates of the same file)
2) Make folders named with the id inside the Cargo folder, and inside those use the "real" name for the document.

I also think Cargo could benefit from an option to "share" files (by means of SFOS Share dialog). Maybe shared files doesn't necessarily need to be saved, but could temporarily reside on /tmp?
Wonder if you could just use [this](https://github.com/sailfishos/sailfish-office/blob/13eb767b68ea6984d4684f561a9afe7ce6f2c8b2/qml/FileListPage.qml#L295)?

**Comment by Logic-gate** [comment]
@attah, hit me up on tg "at Mad_dev".

**Comment by attah** [comment]
No telegram here, sorry. Any chance of seeing you in the #sailfishos channel on Freenode IRC?

**Comment by attah** [comment]
Even with Fernschreiber, i have no idea how to add you.
Anyway, how are things going? Do you want/need me to rebase this PR?

**Comment by Logic-gate** [comment]
Hey, 

Sincerely sorry for the delay...RL. 

I actually need you to take over the project in its entirety. Everything from current fixes to future features. If you don't mind, that is. Including releases; I'll remove Cargo from my repo on OpenRepos. 

I can't maintain it on a regular basis, and you seem to be much more knowledgeable and capable.

**Comment by attah** [comment]
Hmm, i'll have to think about that a bit. I'm not sure i'd be a good maintainer.
I'll take care of this feature, but i'm not sure where the project will go after that.
Maybe asking for a new maintainer on the forum could be a good idea, we'll see.

**Comment by attah** [comment]
Looks like this can can coexist just fine with the conversion logic :)
Do you see anything obvious i should revisit before merging?

**Comment by Logic-gate** [comment]
lgtm. Cheers.

**Pull request merged**
